"use client";

import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import {
  Roboto_Condensed,
  Playfair_Display,
  Krona_One,
} from "next/font/google";

// Font settings
const roboto_condensed = Roboto_Condensed({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-condensed",
});

const playfair_display = Playfair_Display({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair_display",
});

const krona_one = Krona_One({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-krona_one",
});

export const metadata = {
  title: "Romancing Japan",
  description: "Generated by create next app",
};

// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${roboto_condensed.variable} ${playfair_display.variable} ${krona_one.variable}`}
    >
      <body className="bg-base-100">
        <div>
          {/* <Header /> */}
          <Navbar />

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
